<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Pu.Core</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <EmbeddedResource Include="..\..\web\index.html" LogicalName="web.index.html" />
    <EmbeddedResource Include="..\..\web\folder.html" LogicalName="web.folder.html" />
    <EmbeddedResource Include="..\..\web\hls.min.js" LogicalName="web.hls.min.js" />
    <EmbeddedResource Include="..\..\assets\pu-logo.png" LogicalName="assets.pu-logo.png" />
  </ItemGroup>

</Project>
